# ===================================================================
# Spring Boot configuration for the "mil" profile.
#
# This configuration overrides the application.yml file.
#
# ===================================================================
logging: 
    level: 
        ROOT: debug

spring: 
    #激活一个或多个配置
    profiles: 
        active: mil
        include: swagger
    jackson: 
        #格式化输出
        serialization.indent_output: true
        #时区
        time-zone: GMT+8
    jpa: 
        hibername: 
            #使用@Entity时，控制表结构生成行为，none是什么都不做
            ddl-auto: none          
                        
    liquibase: 
        #数据库初始化开关
        enabled: false
        #初始化脚本路径
        change-log: classpath:/db/changelog/master.xml
    redis:
        cluster:
            nodes: node1.zhwg.redis:7001,node2.zhwg.redis:7001,node3.zhwg.redis:7001
    datasource: 
        driverClassName: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://mysqlapp.zhwg.db:28066/bas_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
        username: biyi
        password: Ctsi-nt2jdzyBjJd
        hikari: 
            #最大连接池数
            maximumPoolSize: 20
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    #国际化
    messages: 
        basename: i18n/messages
        encoding: UTF-8
server: 
    #端口号
    port: 9000

ctsi: 
    #新增用户默认密码
    login-password: ctsi1234
    log: 
        #是否启用操作日志
        operation-log: 
            enable: false
        #是否启用登录日志
        login-log: 
            enable: false
    security: 
        authentication: 
            jwt: 
                #token key密钥
                secret: my-secret-token-to-change-in-production
                #token失效时间，秒
                token-validity-in-seconds: 86400
                #rememberme token失效时间
                token-validity-in-seconds-for-remember-me: 2592000   
    captcha: 
        #验证码KEY策略
        keyProvider: simpleCaptchaKeyProvider
        #验证码组件缓存实现，提供两种实现，redis和基于guava的缓存，redis支持集群部署，guava只支持单机使用。可选值：guavaCaptchaCache，redisCaptchaCache
        cache: guavaCaptchaCache
    upload: 
        #biyi-form组件使用，作为模板文件上传的根目录，同时也将作为代码生成的临时目录
        uploadPath: D://tmpfile
    password-check: 
        #密码过期时间，单位 月
        expire-months: 3
        #密码最小长度
        check-min-length: 8
        #密码最大长度
        check-max-length: 20
        #检查密码包含小写字母
        check-lowercase: true
        #检查密码包含大写字母
        check-uppercase: true
        #检查密码包含数字
        check-digit: true
        #检查密码包含键盘相邻字符
        check-keyboard: true
        #检查密码包含特殊字符
        check-special-character: true
    login:
        #密码输错达到次数，锁定用户
        bad-password-attempts: 5
        #锁定时间，单位s
        lockout-time: 3600
        #记录密码错误缓存实现，提供两种实现，redis和基于guava的缓存，redis支持集群部署，guava只支持单机使用。可选值：guavaLoginCache，redisLoginCache
        cache: guavaLoginCache
    access: 
        #组织名
        groupId: ${project.groupId}
        #项目名
        projectName: ${project.artifactId}
        #项目版本
        projectVersion: ${project.version}
        #组件使用用户（比翼平台账号用户名）
        userName: lvdandan
        #是否启用组件统计，关闭则无法上报组件调用量，影响积分
        enable: false
        #统计信息发送地址
        url: https://s.ctbiyi.com/api
        #日志文件
        filePath: /logs
        #发送策略，毫秒
        scheduledRate: 180000
#mybatis配置
mybatis: 
    configLocation: classpath:/mybatis-config.xml

pagehelper: 
    #分页设置
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    pageSizeZero: true

management: 
   health: 
      redis: 
         #关闭REDIS健康检查
         enabled: false

space:
  station-page-url: http://www.zhwg.mil:81/spaceView/#/treeModule
userStationRel:
  syncOrderUrl: http://www.zhwg.mil:81/aiops/oss/a2-data-sync/sync-user-station
  syncAlarmUrl: http://10.0.73.25:26221/auth-rlt-server/api/sm/userStationRel