package com.ctsi.security.domain;

import java.io.Serializable;

/**
 * @author ctsi-biyi-generator
*/
public class BasOrganization implements Serializable {
 
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.org_id
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.org_name
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private String orgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.parent_org_id
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private Long parentOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.org_map_type
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private Short orgMapType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.org_type
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private Short orgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.org_serial
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private String orgSerial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.data_position
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private Short dataPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.org_site_type
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private Short orgSiteType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.delegate_org_id
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private Long delegateOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.delegate_org_position
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private Short delegateOrgPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.trans_flag
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private Integer transFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.data_flag
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private Integer dataFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.admin_district_flag
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private Integer adminDistrictFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.is_oss
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private Byte isOss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.itsm_org_id
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private Long itsmOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.note
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.org_order
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private Integer orgOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.org_level
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private Integer orgLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.org_full_name
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private String orgFullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.res_no
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private String resNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.inner_order
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private String innerOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.inner_code
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private String innerCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.is_valid
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private Byte isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organization.org_path
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    private String orgPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.org_id
     *
     * @return the value of bas_organization.org_id
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.org_id
     *
     * @param orgId the value for bas_organization.org_id
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.org_name
     *
     * @return the value of bas_organization.org_name
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.org_name
     *
     * @param orgName the value for bas_organization.org_name
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.parent_org_id
     *
     * @return the value of bas_organization.parent_org_id
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public Long getParentOrgId() {
        return parentOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.parent_org_id
     *
     * @param parentOrgId the value for bas_organization.parent_org_id
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setParentOrgId(Long parentOrgId) {
        this.parentOrgId = parentOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.org_map_type
     *
     * @return the value of bas_organization.org_map_type
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public Short getOrgMapType() {
        return orgMapType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.org_map_type
     *
     * @param orgMapType the value for bas_organization.org_map_type
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setOrgMapType(Short orgMapType) {
        this.orgMapType = orgMapType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.org_type
     *
     * @return the value of bas_organization.org_type
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public Short getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.org_type
     *
     * @param orgType the value for bas_organization.org_type
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setOrgType(Short orgType) {
        this.orgType = orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.org_serial
     *
     * @return the value of bas_organization.org_serial
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public String getOrgSerial() {
        return orgSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.org_serial
     *
     * @param orgSerial the value for bas_organization.org_serial
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setOrgSerial(String orgSerial) {
        this.orgSerial = orgSerial == null ? null : orgSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.data_position
     *
     * @return the value of bas_organization.data_position
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public Short getDataPosition() {
        return dataPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.data_position
     *
     * @param dataPosition the value for bas_organization.data_position
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setDataPosition(Short dataPosition) {
        this.dataPosition = dataPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.org_site_type
     *
     * @return the value of bas_organization.org_site_type
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public Short getOrgSiteType() {
        return orgSiteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.org_site_type
     *
     * @param orgSiteType the value for bas_organization.org_site_type
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setOrgSiteType(Short orgSiteType) {
        this.orgSiteType = orgSiteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.delegate_org_id
     *
     * @return the value of bas_organization.delegate_org_id
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public Long getDelegateOrgId() {
        return delegateOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.delegate_org_id
     *
     * @param delegateOrgId the value for bas_organization.delegate_org_id
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setDelegateOrgId(Long delegateOrgId) {
        this.delegateOrgId = delegateOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.delegate_org_position
     *
     * @return the value of bas_organization.delegate_org_position
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public Short getDelegateOrgPosition() {
        return delegateOrgPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.delegate_org_position
     *
     * @param delegateOrgPosition the value for bas_organization.delegate_org_position
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setDelegateOrgPosition(Short delegateOrgPosition) {
        this.delegateOrgPosition = delegateOrgPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.trans_flag
     *
     * @return the value of bas_organization.trans_flag
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public Integer getTransFlag() {
        return transFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.trans_flag
     *
     * @param transFlag the value for bas_organization.trans_flag
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setTransFlag(Integer transFlag) {
        this.transFlag = transFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.data_flag
     *
     * @return the value of bas_organization.data_flag
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public Integer getDataFlag() {
        return dataFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.data_flag
     *
     * @param dataFlag the value for bas_organization.data_flag
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setDataFlag(Integer dataFlag) {
        this.dataFlag = dataFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.admin_district_flag
     *
     * @return the value of bas_organization.admin_district_flag
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public Integer getAdminDistrictFlag() {
        return adminDistrictFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.admin_district_flag
     *
     * @param adminDistrictFlag the value for bas_organization.admin_district_flag
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setAdminDistrictFlag(Integer adminDistrictFlag) {
        this.adminDistrictFlag = adminDistrictFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.is_oss
     *
     * @return the value of bas_organization.is_oss
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public Byte getIsOss() {
        return isOss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.is_oss
     *
     * @param isOss the value for bas_organization.is_oss
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setIsOss(Byte isOss) {
        this.isOss = isOss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.itsm_org_id
     *
     * @return the value of bas_organization.itsm_org_id
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public Long getItsmOrgId() {
        return itsmOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.itsm_org_id
     *
     * @param itsmOrgId the value for bas_organization.itsm_org_id
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setItsmOrgId(Long itsmOrgId) {
        this.itsmOrgId = itsmOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.note
     *
     * @return the value of bas_organization.note
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.note
     *
     * @param note the value for bas_organization.note
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.org_order
     *
     * @return the value of bas_organization.org_order
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public Integer getOrgOrder() {
        return orgOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.org_order
     *
     * @param orgOrder the value for bas_organization.org_order
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setOrgOrder(Integer orgOrder) {
        this.orgOrder = orgOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.org_level
     *
     * @return the value of bas_organization.org_level
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public Integer getOrgLevel() {
        return orgLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.org_level
     *
     * @param orgLevel the value for bas_organization.org_level
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setOrgLevel(Integer orgLevel) {
        this.orgLevel = orgLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.org_full_name
     *
     * @return the value of bas_organization.org_full_name
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public String getOrgFullName() {
        return orgFullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.org_full_name
     *
     * @param orgFullName the value for bas_organization.org_full_name
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setOrgFullName(String orgFullName) {
        this.orgFullName = orgFullName == null ? null : orgFullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.res_no
     *
     * @return the value of bas_organization.res_no
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public String getResNo() {
        return resNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.res_no
     *
     * @param resNo the value for bas_organization.res_no
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setResNo(String resNo) {
        this.resNo = resNo == null ? null : resNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.inner_order
     *
     * @return the value of bas_organization.inner_order
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public String getInnerOrder() {
        return innerOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.inner_order
     *
     * @param innerOrder the value for bas_organization.inner_order
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setInnerOrder(String innerOrder) {
        this.innerOrder = innerOrder == null ? null : innerOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.inner_code
     *
     * @return the value of bas_organization.inner_code
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public String getInnerCode() {
        return innerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.inner_code
     *
     * @param innerCode the value for bas_organization.inner_code
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setInnerCode(String innerCode) {
        this.innerCode = innerCode == null ? null : innerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.is_valid
     *
     * @return the value of bas_organization.is_valid
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.is_valid
     *
     * @param isValid the value for bas_organization.is_valid
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organization.org_path
     *
     * @return the value of bas_organization.org_path
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public String getOrgPath() {
        return orgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organization.org_path
     *
     * @param orgPath the value for bas_organization.org_path
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    public void setOrgPath(String orgPath) {
        this.orgPath = orgPath == null ? null : orgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_organization
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BasOrganization other = (BasOrganization) that;
        return (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
            && (this.getOrgName() == null ? other.getOrgName() == null : this.getOrgName().equals(other.getOrgName()))
            && (this.getParentOrgId() == null ? other.getParentOrgId() == null : this.getParentOrgId().equals(other.getParentOrgId()))
            && (this.getOrgMapType() == null ? other.getOrgMapType() == null : this.getOrgMapType().equals(other.getOrgMapType()))
            && (this.getOrgType() == null ? other.getOrgType() == null : this.getOrgType().equals(other.getOrgType()))
            && (this.getOrgSerial() == null ? other.getOrgSerial() == null : this.getOrgSerial().equals(other.getOrgSerial()))
            && (this.getDataPosition() == null ? other.getDataPosition() == null : this.getDataPosition().equals(other.getDataPosition()))
            && (this.getOrgSiteType() == null ? other.getOrgSiteType() == null : this.getOrgSiteType().equals(other.getOrgSiteType()))
            && (this.getDelegateOrgId() == null ? other.getDelegateOrgId() == null : this.getDelegateOrgId().equals(other.getDelegateOrgId()))
            && (this.getDelegateOrgPosition() == null ? other.getDelegateOrgPosition() == null : this.getDelegateOrgPosition().equals(other.getDelegateOrgPosition()))
            && (this.getTransFlag() == null ? other.getTransFlag() == null : this.getTransFlag().equals(other.getTransFlag()))
            && (this.getDataFlag() == null ? other.getDataFlag() == null : this.getDataFlag().equals(other.getDataFlag()))
            && (this.getAdminDistrictFlag() == null ? other.getAdminDistrictFlag() == null : this.getAdminDistrictFlag().equals(other.getAdminDistrictFlag()))
            && (this.getIsOss() == null ? other.getIsOss() == null : this.getIsOss().equals(other.getIsOss()))
            && (this.getItsmOrgId() == null ? other.getItsmOrgId() == null : this.getItsmOrgId().equals(other.getItsmOrgId()))
            && (this.getNote() == null ? other.getNote() == null : this.getNote().equals(other.getNote()))
            && (this.getOrgOrder() == null ? other.getOrgOrder() == null : this.getOrgOrder().equals(other.getOrgOrder()))
            && (this.getOrgLevel() == null ? other.getOrgLevel() == null : this.getOrgLevel().equals(other.getOrgLevel()))
            && (this.getOrgFullName() == null ? other.getOrgFullName() == null : this.getOrgFullName().equals(other.getOrgFullName()))
            && (this.getResNo() == null ? other.getResNo() == null : this.getResNo().equals(other.getResNo()))
            && (this.getInnerOrder() == null ? other.getInnerOrder() == null : this.getInnerOrder().equals(other.getInnerOrder()))
            && (this.getInnerCode() == null ? other.getInnerCode() == null : this.getInnerCode().equals(other.getInnerCode()))
            && (this.getIsValid() == null ? other.getIsValid() == null : this.getIsValid().equals(other.getIsValid()))
            && (this.getOrgPath() == null ? other.getOrgPath() == null : this.getOrgPath().equals(other.getOrgPath()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_organization
     *
     * @mbg.generated Thu Sep 10 15:58:37 GMT+08:00 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        result = prime * result + ((getOrgName() == null) ? 0 : getOrgName().hashCode());
        result = prime * result + ((getParentOrgId() == null) ? 0 : getParentOrgId().hashCode());
        result = prime * result + ((getOrgMapType() == null) ? 0 : getOrgMapType().hashCode());
        result = prime * result + ((getOrgType() == null) ? 0 : getOrgType().hashCode());
        result = prime * result + ((getOrgSerial() == null) ? 0 : getOrgSerial().hashCode());
        result = prime * result + ((getDataPosition() == null) ? 0 : getDataPosition().hashCode());
        result = prime * result + ((getOrgSiteType() == null) ? 0 : getOrgSiteType().hashCode());
        result = prime * result + ((getDelegateOrgId() == null) ? 0 : getDelegateOrgId().hashCode());
        result = prime * result + ((getDelegateOrgPosition() == null) ? 0 : getDelegateOrgPosition().hashCode());
        result = prime * result + ((getTransFlag() == null) ? 0 : getTransFlag().hashCode());
        result = prime * result + ((getDataFlag() == null) ? 0 : getDataFlag().hashCode());
        result = prime * result + ((getAdminDistrictFlag() == null) ? 0 : getAdminDistrictFlag().hashCode());
        result = prime * result + ((getIsOss() == null) ? 0 : getIsOss().hashCode());
        result = prime * result + ((getItsmOrgId() == null) ? 0 : getItsmOrgId().hashCode());
        result = prime * result + ((getNote() == null) ? 0 : getNote().hashCode());
        result = prime * result + ((getOrgOrder() == null) ? 0 : getOrgOrder().hashCode());
        result = prime * result + ((getOrgLevel() == null) ? 0 : getOrgLevel().hashCode());
        result = prime * result + ((getOrgFullName() == null) ? 0 : getOrgFullName().hashCode());
        result = prime * result + ((getResNo() == null) ? 0 : getResNo().hashCode());
        result = prime * result + ((getInnerOrder() == null) ? 0 : getInnerOrder().hashCode());
        result = prime * result + ((getInnerCode() == null) ? 0 : getInnerCode().hashCode());
        result = prime * result + ((getIsValid() == null) ? 0 : getIsValid().hashCode());
        result = prime * result + ((getOrgPath() == null) ? 0 : getOrgPath().hashCode());
        return result;
    }
}