package com.ctsi.security.domain;

import java.io.Serializable;
import java.time.ZonedDateTime;

/**
 * @author ctsi-biyi-generator
*/
public class BasUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_user.user_id
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_user.user_name
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_user.user_mode
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    private Byte userMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_user.user_type_id
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    private Long userTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_user.user_login_name
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    private String userLoginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_user.user_password
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_user.user_valid
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    private Byte userValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_user.user_work_num
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    private String userWorkNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_user.user_tel
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    private String userTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_user.user_email
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_user.user_fax
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    private String userFax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_user.note
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_user.center_nms
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    private Long centerNms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_user.org_id
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_user.oa_user_id
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    private String oaUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_user.person_id
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    private String personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_user.status
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_user.update_time
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    private ZonedDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_user.user_id
     *
     * @return the value of bas_user.user_id
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_user.user_id
     *
     * @param userId the value for bas_user.user_id
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_user.user_name
     *
     * @return the value of bas_user.user_name
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_user.user_name
     *
     * @param userName the value for bas_user.user_name
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_user.user_mode
     *
     * @return the value of bas_user.user_mode
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public Byte getUserMode() {
        return userMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_user.user_mode
     *
     * @param userMode the value for bas_user.user_mode
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public void setUserMode(Byte userMode) {
        this.userMode = userMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_user.user_type_id
     *
     * @return the value of bas_user.user_type_id
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public Long getUserTypeId() {
        return userTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_user.user_type_id
     *
     * @param userTypeId the value for bas_user.user_type_id
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public void setUserTypeId(Long userTypeId) {
        this.userTypeId = userTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_user.user_login_name
     *
     * @return the value of bas_user.user_login_name
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public String getUserLoginName() {
        return userLoginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_user.user_login_name
     *
     * @param userLoginName the value for bas_user.user_login_name
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public void setUserLoginName(String userLoginName) {
        this.userLoginName = userLoginName == null ? null : userLoginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_user.user_password
     *
     * @return the value of bas_user.user_password
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_user.user_password
     *
     * @param userPassword the value for bas_user.user_password
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_user.user_valid
     *
     * @return the value of bas_user.user_valid
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public Byte getUserValid() {
        return userValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_user.user_valid
     *
     * @param userValid the value for bas_user.user_valid
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public void setUserValid(Byte userValid) {
        this.userValid = userValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_user.user_work_num
     *
     * @return the value of bas_user.user_work_num
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public String getUserWorkNum() {
        return userWorkNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_user.user_work_num
     *
     * @param userWorkNum the value for bas_user.user_work_num
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public void setUserWorkNum(String userWorkNum) {
        this.userWorkNum = userWorkNum == null ? null : userWorkNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_user.user_tel
     *
     * @return the value of bas_user.user_tel
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_user.user_tel
     *
     * @param userTel the value for bas_user.user_tel
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel == null ? null : userTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_user.user_email
     *
     * @return the value of bas_user.user_email
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_user.user_email
     *
     * @param userEmail the value for bas_user.user_email
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_user.user_fax
     *
     * @return the value of bas_user.user_fax
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public String getUserFax() {
        return userFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_user.user_fax
     *
     * @param userFax the value for bas_user.user_fax
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public void setUserFax(String userFax) {
        this.userFax = userFax == null ? null : userFax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_user.note
     *
     * @return the value of bas_user.note
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_user.note
     *
     * @param note the value for bas_user.note
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_user.center_nms
     *
     * @return the value of bas_user.center_nms
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public Long getCenterNms() {
        return centerNms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_user.center_nms
     *
     * @param centerNms the value for bas_user.center_nms
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public void setCenterNms(Long centerNms) {
        this.centerNms = centerNms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_user.org_id
     *
     * @return the value of bas_user.org_id
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_user.org_id
     *
     * @param orgId the value for bas_user.org_id
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_user.oa_user_id
     *
     * @return the value of bas_user.oa_user_id
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public String getOaUserId() {
        return oaUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_user.oa_user_id
     *
     * @param oaUserId the value for bas_user.oa_user_id
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public void setOaUserId(String oaUserId) {
        this.oaUserId = oaUserId == null ? null : oaUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_user.person_id
     *
     * @return the value of bas_user.person_id
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_user.person_id
     *
     * @param personId the value for bas_user.person_id
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public void setPersonId(String personId) {
        this.personId = personId == null ? null : personId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_user.status
     *
     * @return the value of bas_user.status
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_user.status
     *
     * @param status the value for bas_user.status
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_user.update_time
     *
     * @return the value of bas_user.update_time
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public ZonedDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_user.update_time
     *
     * @param updateTime the value for bas_user.update_time
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    public void setUpdateTime(ZonedDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_user
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BasUser other = (BasUser) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getUserMode() == null ? other.getUserMode() == null : this.getUserMode().equals(other.getUserMode()))
            && (this.getUserTypeId() == null ? other.getUserTypeId() == null : this.getUserTypeId().equals(other.getUserTypeId()))
            && (this.getUserLoginName() == null ? other.getUserLoginName() == null : this.getUserLoginName().equals(other.getUserLoginName()))
            && (this.getUserPassword() == null ? other.getUserPassword() == null : this.getUserPassword().equals(other.getUserPassword()))
            && (this.getUserValid() == null ? other.getUserValid() == null : this.getUserValid().equals(other.getUserValid()))
            && (this.getUserWorkNum() == null ? other.getUserWorkNum() == null : this.getUserWorkNum().equals(other.getUserWorkNum()))
            && (this.getUserTel() == null ? other.getUserTel() == null : this.getUserTel().equals(other.getUserTel()))
            && (this.getUserEmail() == null ? other.getUserEmail() == null : this.getUserEmail().equals(other.getUserEmail()))
            && (this.getUserFax() == null ? other.getUserFax() == null : this.getUserFax().equals(other.getUserFax()))
            && (this.getNote() == null ? other.getNote() == null : this.getNote().equals(other.getNote()))
            && (this.getCenterNms() == null ? other.getCenterNms() == null : this.getCenterNms().equals(other.getCenterNms()))
            && (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
            && (this.getOaUserId() == null ? other.getOaUserId() == null : this.getOaUserId().equals(other.getOaUserId()))
            && (this.getPersonId() == null ? other.getPersonId() == null : this.getPersonId().equals(other.getPersonId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_user
     *
     * @mbg.generated Fri Sep 18 10:12:01 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getUserMode() == null) ? 0 : getUserMode().hashCode());
        result = prime * result + ((getUserTypeId() == null) ? 0 : getUserTypeId().hashCode());
        result = prime * result + ((getUserLoginName() == null) ? 0 : getUserLoginName().hashCode());
        result = prime * result + ((getUserPassword() == null) ? 0 : getUserPassword().hashCode());
        result = prime * result + ((getUserValid() == null) ? 0 : getUserValid().hashCode());
        result = prime * result + ((getUserWorkNum() == null) ? 0 : getUserWorkNum().hashCode());
        result = prime * result + ((getUserTel() == null) ? 0 : getUserTel().hashCode());
        result = prime * result + ((getUserEmail() == null) ? 0 : getUserEmail().hashCode());
        result = prime * result + ((getUserFax() == null) ? 0 : getUserFax().hashCode());
        result = prime * result + ((getNote() == null) ? 0 : getNote().hashCode());
        result = prime * result + ((getCenterNms() == null) ? 0 : getCenterNms().hashCode());
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        result = prime * result + ((getOaUserId() == null) ? 0 : getOaUserId().hashCode());
        result = prime * result + ((getPersonId() == null) ? 0 : getPersonId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}