package com.ctsi.space.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.ZonedDateTime;

/**
 * @author ctsi-biyi-generator
*/
public class BasStation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.station_id
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private Long stationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.res_no
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private String resNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.station_name
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private String stationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.station_type
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private Long stationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.admin_district_id
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private Long adminDistrictId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.org_id
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.org_type
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private Long orgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.station_order
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private Long stationOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.station_tel
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private String stationTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.station_address
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private String stationAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.coordinate_x
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private BigDecimal coordinateX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.coordinate_y
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private BigDecimal coordinateY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.coordinate_z
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private BigDecimal coordinateZ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.note
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.protect_unit
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private String protectUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.duty_type
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private Long dutyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.cdma_node_task
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private String cdmaNodeTask;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.station_owner
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private Long stationOwner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.theater_id
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private Long theaterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.army_type
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private Long armyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.is_liable
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private Long isLiable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.duty_num
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private Long dutyNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.station_unknown_flg
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private Byte stationUnknownFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.station_valid
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private Byte stationValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.company
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_station.update_timestamp
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    private ZonedDateTime updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.station_id
     *
     * @return the value of bas_station.station_id
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public Long getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.station_id
     *
     * @param stationId the value for bas_station.station_id
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setStationId(Long stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.res_no
     *
     * @return the value of bas_station.res_no
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public String getResNo() {
        return resNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.res_no
     *
     * @param resNo the value for bas_station.res_no
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setResNo(String resNo) {
        this.resNo = resNo == null ? null : resNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.station_name
     *
     * @return the value of bas_station.station_name
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.station_name
     *
     * @param stationName the value for bas_station.station_name
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setStationName(String stationName) {
        this.stationName = stationName == null ? null : stationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.station_type
     *
     * @return the value of bas_station.station_type
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public Long getStationType() {
        return stationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.station_type
     *
     * @param stationType the value for bas_station.station_type
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setStationType(Long stationType) {
        this.stationType = stationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.admin_district_id
     *
     * @return the value of bas_station.admin_district_id
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public Long getAdminDistrictId() {
        return adminDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.admin_district_id
     *
     * @param adminDistrictId the value for bas_station.admin_district_id
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setAdminDistrictId(Long adminDistrictId) {
        this.adminDistrictId = adminDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.org_id
     *
     * @return the value of bas_station.org_id
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.org_id
     *
     * @param orgId the value for bas_station.org_id
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.org_type
     *
     * @return the value of bas_station.org_type
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public Long getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.org_type
     *
     * @param orgType the value for bas_station.org_type
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setOrgType(Long orgType) {
        this.orgType = orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.station_order
     *
     * @return the value of bas_station.station_order
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public Long getStationOrder() {
        return stationOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.station_order
     *
     * @param stationOrder the value for bas_station.station_order
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setStationOrder(Long stationOrder) {
        this.stationOrder = stationOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.station_tel
     *
     * @return the value of bas_station.station_tel
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public String getStationTel() {
        return stationTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.station_tel
     *
     * @param stationTel the value for bas_station.station_tel
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setStationTel(String stationTel) {
        this.stationTel = stationTel == null ? null : stationTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.station_address
     *
     * @return the value of bas_station.station_address
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public String getStationAddress() {
        return stationAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.station_address
     *
     * @param stationAddress the value for bas_station.station_address
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setStationAddress(String stationAddress) {
        this.stationAddress = stationAddress == null ? null : stationAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.coordinate_x
     *
     * @return the value of bas_station.coordinate_x
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public BigDecimal getCoordinateX() {
        return coordinateX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.coordinate_x
     *
     * @param coordinateX the value for bas_station.coordinate_x
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setCoordinateX(BigDecimal coordinateX) {
        this.coordinateX = coordinateX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.coordinate_y
     *
     * @return the value of bas_station.coordinate_y
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public BigDecimal getCoordinateY() {
        return coordinateY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.coordinate_y
     *
     * @param coordinateY the value for bas_station.coordinate_y
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setCoordinateY(BigDecimal coordinateY) {
        this.coordinateY = coordinateY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.coordinate_z
     *
     * @return the value of bas_station.coordinate_z
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public BigDecimal getCoordinateZ() {
        return coordinateZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.coordinate_z
     *
     * @param coordinateZ the value for bas_station.coordinate_z
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setCoordinateZ(BigDecimal coordinateZ) {
        this.coordinateZ = coordinateZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.note
     *
     * @return the value of bas_station.note
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.note
     *
     * @param note the value for bas_station.note
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.protect_unit
     *
     * @return the value of bas_station.protect_unit
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public String getProtectUnit() {
        return protectUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.protect_unit
     *
     * @param protectUnit the value for bas_station.protect_unit
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setProtectUnit(String protectUnit) {
        this.protectUnit = protectUnit == null ? null : protectUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.duty_type
     *
     * @return the value of bas_station.duty_type
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public Long getDutyType() {
        return dutyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.duty_type
     *
     * @param dutyType the value for bas_station.duty_type
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setDutyType(Long dutyType) {
        this.dutyType = dutyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.cdma_node_task
     *
     * @return the value of bas_station.cdma_node_task
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public String getCdmaNodeTask() {
        return cdmaNodeTask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.cdma_node_task
     *
     * @param cdmaNodeTask the value for bas_station.cdma_node_task
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setCdmaNodeTask(String cdmaNodeTask) {
        this.cdmaNodeTask = cdmaNodeTask == null ? null : cdmaNodeTask.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.station_owner
     *
     * @return the value of bas_station.station_owner
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public Long getStationOwner() {
        return stationOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.station_owner
     *
     * @param stationOwner the value for bas_station.station_owner
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setStationOwner(Long stationOwner) {
        this.stationOwner = stationOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.theater_id
     *
     * @return the value of bas_station.theater_id
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public Long getTheaterId() {
        return theaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.theater_id
     *
     * @param theaterId the value for bas_station.theater_id
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setTheaterId(Long theaterId) {
        this.theaterId = theaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.army_type
     *
     * @return the value of bas_station.army_type
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public Long getArmyType() {
        return armyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.army_type
     *
     * @param armyType the value for bas_station.army_type
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setArmyType(Long armyType) {
        this.armyType = armyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.is_liable
     *
     * @return the value of bas_station.is_liable
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public Long getIsLiable() {
        return isLiable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.is_liable
     *
     * @param isLiable the value for bas_station.is_liable
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setIsLiable(Long isLiable) {
        this.isLiable = isLiable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.duty_num
     *
     * @return the value of bas_station.duty_num
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public Long getDutyNum() {
        return dutyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.duty_num
     *
     * @param dutyNum the value for bas_station.duty_num
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setDutyNum(Long dutyNum) {
        this.dutyNum = dutyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.station_unknown_flg
     *
     * @return the value of bas_station.station_unknown_flg
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public Byte getStationUnknownFlg() {
        return stationUnknownFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.station_unknown_flg
     *
     * @param stationUnknownFlg the value for bas_station.station_unknown_flg
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setStationUnknownFlg(Byte stationUnknownFlg) {
        this.stationUnknownFlg = stationUnknownFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.station_valid
     *
     * @return the value of bas_station.station_valid
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public Byte getStationValid() {
        return stationValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.station_valid
     *
     * @param stationValid the value for bas_station.station_valid
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setStationValid(Byte stationValid) {
        this.stationValid = stationValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.company
     *
     * @return the value of bas_station.company
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.company
     *
     * @param company the value for bas_station.company
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_station.update_timestamp
     *
     * @return the value of bas_station.update_timestamp
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public ZonedDateTime getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_station.update_timestamp
     *
     * @param updateTimestamp the value for bas_station.update_timestamp
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    public void setUpdateTimestamp(ZonedDateTime updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_station
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BasStation other = (BasStation) that;
        return (this.getStationId() == null ? other.getStationId() == null : this.getStationId().equals(other.getStationId()))
            && (this.getResNo() == null ? other.getResNo() == null : this.getResNo().equals(other.getResNo()))
            && (this.getStationName() == null ? other.getStationName() == null : this.getStationName().equals(other.getStationName()))
            && (this.getStationType() == null ? other.getStationType() == null : this.getStationType().equals(other.getStationType()))
            && (this.getAdminDistrictId() == null ? other.getAdminDistrictId() == null : this.getAdminDistrictId().equals(other.getAdminDistrictId()))
            && (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
            && (this.getOrgType() == null ? other.getOrgType() == null : this.getOrgType().equals(other.getOrgType()))
            && (this.getStationOrder() == null ? other.getStationOrder() == null : this.getStationOrder().equals(other.getStationOrder()))
            && (this.getStationTel() == null ? other.getStationTel() == null : this.getStationTel().equals(other.getStationTel()))
            && (this.getStationAddress() == null ? other.getStationAddress() == null : this.getStationAddress().equals(other.getStationAddress()))
            && (this.getCoordinateX() == null ? other.getCoordinateX() == null : this.getCoordinateX().equals(other.getCoordinateX()))
            && (this.getCoordinateY() == null ? other.getCoordinateY() == null : this.getCoordinateY().equals(other.getCoordinateY()))
            && (this.getCoordinateZ() == null ? other.getCoordinateZ() == null : this.getCoordinateZ().equals(other.getCoordinateZ()))
            && (this.getNote() == null ? other.getNote() == null : this.getNote().equals(other.getNote()))
            && (this.getProtectUnit() == null ? other.getProtectUnit() == null : this.getProtectUnit().equals(other.getProtectUnit()))
            && (this.getDutyType() == null ? other.getDutyType() == null : this.getDutyType().equals(other.getDutyType()))
            && (this.getCdmaNodeTask() == null ? other.getCdmaNodeTask() == null : this.getCdmaNodeTask().equals(other.getCdmaNodeTask()))
            && (this.getStationOwner() == null ? other.getStationOwner() == null : this.getStationOwner().equals(other.getStationOwner()))
            && (this.getTheaterId() == null ? other.getTheaterId() == null : this.getTheaterId().equals(other.getTheaterId()))
            && (this.getArmyType() == null ? other.getArmyType() == null : this.getArmyType().equals(other.getArmyType()))
            && (this.getIsLiable() == null ? other.getIsLiable() == null : this.getIsLiable().equals(other.getIsLiable()))
            && (this.getDutyNum() == null ? other.getDutyNum() == null : this.getDutyNum().equals(other.getDutyNum()))
            && (this.getStationUnknownFlg() == null ? other.getStationUnknownFlg() == null : this.getStationUnknownFlg().equals(other.getStationUnknownFlg()))
            && (this.getStationValid() == null ? other.getStationValid() == null : this.getStationValid().equals(other.getStationValid()))
            && (this.getCompany() == null ? other.getCompany() == null : this.getCompany().equals(other.getCompany()))
            && (this.getUpdateTimestamp() == null ? other.getUpdateTimestamp() == null : this.getUpdateTimestamp().equals(other.getUpdateTimestamp()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_station
     *
     * @mbg.generated Mon Sep 14 11:17:32 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getStationId() == null) ? 0 : getStationId().hashCode());
        result = prime * result + ((getResNo() == null) ? 0 : getResNo().hashCode());
        result = prime * result + ((getStationName() == null) ? 0 : getStationName().hashCode());
        result = prime * result + ((getStationType() == null) ? 0 : getStationType().hashCode());
        result = prime * result + ((getAdminDistrictId() == null) ? 0 : getAdminDistrictId().hashCode());
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        result = prime * result + ((getOrgType() == null) ? 0 : getOrgType().hashCode());
        result = prime * result + ((getStationOrder() == null) ? 0 : getStationOrder().hashCode());
        result = prime * result + ((getStationTel() == null) ? 0 : getStationTel().hashCode());
        result = prime * result + ((getStationAddress() == null) ? 0 : getStationAddress().hashCode());
        result = prime * result + ((getCoordinateX() == null) ? 0 : getCoordinateX().hashCode());
        result = prime * result + ((getCoordinateY() == null) ? 0 : getCoordinateY().hashCode());
        result = prime * result + ((getCoordinateZ() == null) ? 0 : getCoordinateZ().hashCode());
        result = prime * result + ((getNote() == null) ? 0 : getNote().hashCode());
        result = prime * result + ((getProtectUnit() == null) ? 0 : getProtectUnit().hashCode());
        result = prime * result + ((getDutyType() == null) ? 0 : getDutyType().hashCode());
        result = prime * result + ((getCdmaNodeTask() == null) ? 0 : getCdmaNodeTask().hashCode());
        result = prime * result + ((getStationOwner() == null) ? 0 : getStationOwner().hashCode());
        result = prime * result + ((getTheaterId() == null) ? 0 : getTheaterId().hashCode());
        result = prime * result + ((getArmyType() == null) ? 0 : getArmyType().hashCode());
        result = prime * result + ((getIsLiable() == null) ? 0 : getIsLiable().hashCode());
        result = prime * result + ((getDutyNum() == null) ? 0 : getDutyNum().hashCode());
        result = prime * result + ((getStationUnknownFlg() == null) ? 0 : getStationUnknownFlg().hashCode());
        result = prime * result + ((getStationValid() == null) ? 0 : getStationValid().hashCode());
        result = prime * result + ((getCompany() == null) ? 0 : getCompany().hashCode());
        result = prime * result + ((getUpdateTimestamp() == null) ? 0 : getUpdateTimestamp().hashCode());
        return result;
    }
}