package com.ctsi.block.repository;

import com.ctsi.block.domain.BlockedSystem;
import com.ctsi.block.domain.BlockedSystemExample.Criteria;
import com.ctsi.block.domain.BlockedSystemExample.Criterion;
import com.ctsi.block.domain.BlockedSystemExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

/**
 * @author ctsi-biyi-generator
*/
public class BlockedSystemSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public String countByExample(BlockedSystemExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("blocked_system");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public String deleteByExample(BlockedSystemExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("blocked_system");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public String insertSelective(BlockedSystem record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("blocked_system");
        
        if (record.getAffactId() != null) {
            sql.VALUES("affact_id", "#{affactId,jdbcType=DECIMAL}");
        }
        
        if (record.getBlockedId() != null) {
            sql.VALUES("blocked_id", "#{blockedId,jdbcType=DECIMAL}");
        }
        
        if (record.getDataResource() != null) {
            sql.VALUES("data_resource", "#{dataResource,jdbcType=DECIMAL}");
        }
        
        if (record.getSystemType() != null) {
            sql.VALUES("system_type", "#{systemType,jdbcType=DECIMAL}");
        }
        
        if (record.getSystemId() != null) {
            sql.VALUES("system_id", "#{systemId,jdbcType=DECIMAL}");
        }
        
        if (record.getSystemName() != null) {
            sql.VALUES("system_name", "#{systemName,jdbcType=VARCHAR}");
        }
        
        if (record.getSystemMark() != null) {
            sql.VALUES("system_mark", "#{systemMark,jdbcType=VARCHAR}");
        }
        
        if (record.getSystemLevel() != null) {
            sql.VALUES("system_level", "#{systemLevel,jdbcType=DECIMAL}");
        }
        
        if (record.getSystemAlias() != null) {
            sql.VALUES("system_alias", "#{systemAlias,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public String selectByExample(BlockedSystemExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("affact_id");
        } else {
            sql.SELECT("affact_id");
        }
        sql.SELECT("blocked_id");
        sql.SELECT("data_resource");
        sql.SELECT("system_type");
        sql.SELECT("system_id");
        sql.SELECT("system_name");
        sql.SELECT("system_mark");
        sql.SELECT("system_level");
        sql.SELECT("system_alias");
        sql.FROM("blocked_system");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        BlockedSystem record = (BlockedSystem) parameter.get("record");
        BlockedSystemExample example = (BlockedSystemExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("blocked_system");
        
        if (record.getAffactId() != null) {
            sql.SET("affact_id = #{record.affactId,jdbcType=DECIMAL}");
        }
        
        if (record.getBlockedId() != null) {
            sql.SET("blocked_id = #{record.blockedId,jdbcType=DECIMAL}");
        }
        
        if (record.getDataResource() != null) {
            sql.SET("data_resource = #{record.dataResource,jdbcType=DECIMAL}");
        }
        
        if (record.getSystemType() != null) {
            sql.SET("system_type = #{record.systemType,jdbcType=DECIMAL}");
        }
        
        if (record.getSystemId() != null) {
            sql.SET("system_id = #{record.systemId,jdbcType=DECIMAL}");
        }
        
        if (record.getSystemName() != null) {
            sql.SET("system_name = #{record.systemName,jdbcType=VARCHAR}");
        }
        
        if (record.getSystemMark() != null) {
            sql.SET("system_mark = #{record.systemMark,jdbcType=VARCHAR}");
        }
        
        if (record.getSystemLevel() != null) {
            sql.SET("system_level = #{record.systemLevel,jdbcType=DECIMAL}");
        }
        
        if (record.getSystemAlias() != null) {
            sql.SET("system_alias = #{record.systemAlias,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("blocked_system");
        
        sql.SET("affact_id = #{record.affactId,jdbcType=DECIMAL}");
        sql.SET("blocked_id = #{record.blockedId,jdbcType=DECIMAL}");
        sql.SET("data_resource = #{record.dataResource,jdbcType=DECIMAL}");
        sql.SET("system_type = #{record.systemType,jdbcType=DECIMAL}");
        sql.SET("system_id = #{record.systemId,jdbcType=DECIMAL}");
        sql.SET("system_name = #{record.systemName,jdbcType=VARCHAR}");
        sql.SET("system_mark = #{record.systemMark,jdbcType=VARCHAR}");
        sql.SET("system_level = #{record.systemLevel,jdbcType=DECIMAL}");
        sql.SET("system_alias = #{record.systemAlias,jdbcType=VARCHAR}");
        
        BlockedSystemExample example = (BlockedSystemExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    protected void applyWhere(SQL sql, BlockedSystemExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}