package com.ctsi.block.domain;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.time.ZonedDateTime;
import java.util.Date;


/**
 * @author ctsi-biyi-generator
*/
public class BlockedInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.blocked_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long blockedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.is_valid
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.specility_type
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long specilityType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.trans_level
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long transLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.start_date
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    //@JsonFormat(pattern = "yyyy-MM-dd HH:mm",timezone="GMT+8")
    private ZonedDateTime startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.stop_date
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    //@JsonFormat(pattern = "yyyy-MM-dd HH:mm",timezone="GMT+8")
    private ZonedDateTime stopDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.blocked_duration
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Double blockedDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.admin_distirct_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long adminDistirctId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.maint_org_type
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long maintOrgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.maint_org_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long maintOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.maint_org
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private String maintOrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.charge_range
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long chargeRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.blocked_type
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long blockedType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.blocked_reason
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long blockedReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.opt_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long optId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.opt_name
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private String optName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.opt_seg_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long optSegId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.opt_seg_name
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private String optSegName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.station_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long stationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.station_name
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private String stationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.is_cnt_times
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long isCntTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.is_cnt_duration
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long isCntDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.blocked_detail
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private String blockedDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.affact_range
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private String affactRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.blocked_state
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long blockedState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.claim_state
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long claimState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.user_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.org_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.commit_date
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    //@JsonFormat(pattern = "yyyy-MM-dd HH:mm",timezone="GMT+8")
    private ZonedDateTime commitDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.lv_checker
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long lvChecker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.lv_check_date
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    //@JsonFormat(pattern = "yyyy-MM-dd HH:mm",timezone="GMT+8")
    private ZonedDateTime lvCheckDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.lv_check_state
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    //@JsonFormat(pattern = "yyyy-MM-dd HH:mm",timezone="GMT+8")
    private Long lvCheckState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.base_checker
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long baseChecker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.base_check_date
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    //@JsonFormat(pattern = "yyyy-MM-dd HH:mm",timezone="GMT+8")
    private ZonedDateTime baseCheckDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.base_check_state
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long baseCheckState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.modify_user
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    private Long modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_info.modify_date
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    //@JsonFormat(pattern = "yyyy-MM-dd HH:mm",timezone="GMT+8")
    private ZonedDateTime modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.blocked_id
     *
     * @return the value of blocked_info.blocked_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getBlockedId() {
        return blockedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.blocked_id
     *
     * @param blockedId the value for blocked_info.blocked_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setBlockedId(Long blockedId) {
        this.blockedId = blockedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.is_valid
     *
     * @return the value of blocked_info.is_valid
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.is_valid
     *
     * @param isValid the value for blocked_info.is_valid
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setIsValid(Long isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.specility_type
     *
     * @return the value of blocked_info.specility_type
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getSpecilityType() {
        return specilityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.specility_type
     *
     * @param specilityType the value for blocked_info.specility_type
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setSpecilityType(Long specilityType) {
        this.specilityType = specilityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.trans_level
     *
     * @return the value of blocked_info.trans_level
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getTransLevel() {
        return transLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.trans_level
     *
     * @param transLevel the value for blocked_info.trans_level
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setTransLevel(Long transLevel) {
        this.transLevel = transLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.start_date
     *
     * @return the value of blocked_info.start_date
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public ZonedDateTime getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.start_date
     *
     * @param startDate the value for blocked_info.start_date
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setStartDate(ZonedDateTime startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.stop_date
     *
     * @return the value of blocked_info.stop_date
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public ZonedDateTime getStopDate() {
        return stopDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.stop_date
     *
     * @param stopDate the value for blocked_info.stop_date
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setStopDate(ZonedDateTime stopDate) {
        this.stopDate = stopDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.blocked_duration
     *
     * @return the value of blocked_info.blocked_duration
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Double getBlockedDuration() {
        return blockedDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.blocked_duration
     *
     * @param blockedDuration the value for blocked_info.blocked_duration
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setBlockedDuration(Double blockedDuration) {
        this.blockedDuration = blockedDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.admin_distirct_id
     *
     * @return the value of blocked_info.admin_distirct_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getAdminDistirctId() {
        return adminDistirctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.admin_distirct_id
     *
     * @param adminDistirctId the value for blocked_info.admin_distirct_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setAdminDistirctId(Long adminDistirctId) {
        this.adminDistirctId = adminDistirctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.maint_org_type
     *
     * @return the value of blocked_info.maint_org_type
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getMaintOrgType() {
        return maintOrgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.maint_org_type
     *
     * @param maintOrgType the value for blocked_info.maint_org_type
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setMaintOrgType(Long maintOrgType) {
        this.maintOrgType = maintOrgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.maint_org_id
     *
     * @return the value of blocked_info.maint_org_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getMaintOrgId() {
        return maintOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.maint_org_id
     *
     * @param maintOrgId the value for blocked_info.maint_org_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setMaintOrgId(Long maintOrgId) {
        this.maintOrgId = maintOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.maint_org
     *
     * @return the value of blocked_info.maint_org
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public String getMaintOrg() {
        return maintOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.maint_org
     *
     * @param maintOrg the value for blocked_info.maint_org
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setMaintOrg(String maintOrg) {
        this.maintOrg = maintOrg == null ? null : maintOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.charge_range
     *
     * @return the value of blocked_info.charge_range
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getChargeRange() {
        return chargeRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.charge_range
     *
     * @param chargeRange the value for blocked_info.charge_range
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setChargeRange(Long chargeRange) {
        this.chargeRange = chargeRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.blocked_type
     *
     * @return the value of blocked_info.blocked_type
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getBlockedType() {
        return blockedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.blocked_type
     *
     * @param blockedType the value for blocked_info.blocked_type
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setBlockedType(Long blockedType) {
        this.blockedType = blockedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.blocked_reason
     *
     * @return the value of blocked_info.blocked_reason
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getBlockedReason() {
        return blockedReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.blocked_reason
     *
     * @param blockedReason the value for blocked_info.blocked_reason
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setBlockedReason(Long blockedReason) {
        this.blockedReason = blockedReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.opt_id
     *
     * @return the value of blocked_info.opt_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getOptId() {
        return optId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.opt_id
     *
     * @param optId the value for blocked_info.opt_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setOptId(Long optId) {
        this.optId = optId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.opt_name
     *
     * @return the value of blocked_info.opt_name
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public String getOptName() {
        return optName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.opt_name
     *
     * @param optName the value for blocked_info.opt_name
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setOptName(String optName) {
        this.optName = optName == null ? null : optName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.opt_seg_id
     *
     * @return the value of blocked_info.opt_seg_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getOptSegId() {
        return optSegId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.opt_seg_id
     *
     * @param optSegId the value for blocked_info.opt_seg_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setOptSegId(Long optSegId) {
        this.optSegId = optSegId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.opt_seg_name
     *
     * @return the value of blocked_info.opt_seg_name
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public String getOptSegName() {
        return optSegName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.opt_seg_name
     *
     * @param optSegName the value for blocked_info.opt_seg_name
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setOptSegName(String optSegName) {
        this.optSegName = optSegName == null ? null : optSegName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.station_id
     *
     * @return the value of blocked_info.station_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.station_id
     *
     * @param stationId the value for blocked_info.station_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setStationId(Long stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.station_name
     *
     * @return the value of blocked_info.station_name
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.station_name
     *
     * @param stationName the value for blocked_info.station_name
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setStationName(String stationName) {
        this.stationName = stationName == null ? null : stationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.is_cnt_times
     *
     * @return the value of blocked_info.is_cnt_times
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getIsCntTimes() {
        return isCntTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.is_cnt_times
     *
     * @param isCntTimes the value for blocked_info.is_cnt_times
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setIsCntTimes(Long isCntTimes) {
        this.isCntTimes = isCntTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.is_cnt_duration
     *
     * @return the value of blocked_info.is_cnt_duration
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getIsCntDuration() {
        return isCntDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.is_cnt_duration
     *
     * @param isCntDuration the value for blocked_info.is_cnt_duration
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setIsCntDuration(Long isCntDuration) {
        this.isCntDuration = isCntDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.blocked_detail
     *
     * @return the value of blocked_info.blocked_detail
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public String getBlockedDetail() {
        return blockedDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.blocked_detail
     *
     * @param blockedDetail the value for blocked_info.blocked_detail
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setBlockedDetail(String blockedDetail) {
        this.blockedDetail = blockedDetail == null ? null : blockedDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.affact_range
     *
     * @return the value of blocked_info.affact_range
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public String getAffactRange() {
        return affactRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.affact_range
     *
     * @param affactRange the value for blocked_info.affact_range
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setAffactRange(String affactRange) {
        this.affactRange = affactRange == null ? null : affactRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.blocked_state
     *
     * @return the value of blocked_info.blocked_state
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getBlockedState() {
        return blockedState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.blocked_state
     *
     * @param blockedState the value for blocked_info.blocked_state
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setBlockedState(Long blockedState) {
        this.blockedState = blockedState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.claim_state
     *
     * @return the value of blocked_info.claim_state
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getClaimState() {
        return claimState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.claim_state
     *
     * @param claimState the value for blocked_info.claim_state
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setClaimState(Long claimState) {
        this.claimState = claimState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.user_id
     *
     * @return the value of blocked_info.user_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.user_id
     *
     * @param userId the value for blocked_info.user_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.org_id
     *
     * @return the value of blocked_info.org_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.org_id
     *
     * @param orgId the value for blocked_info.org_id
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.commit_date
     *
     * @return the value of blocked_info.commit_date
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public ZonedDateTime getCommitDate() {
        return commitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.commit_date
     *
     * @param commitDate the value for blocked_info.commit_date
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setCommitDate(ZonedDateTime commitDate) {
        this.commitDate = commitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.lv_checker
     *
     * @return the value of blocked_info.lv_checker
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getLvChecker() {
        return lvChecker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.lv_checker
     *
     * @param lvChecker the value for blocked_info.lv_checker
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setLvChecker(Long lvChecker) {
        this.lvChecker = lvChecker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.lv_check_date
     *
     * @return the value of blocked_info.lv_check_date
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public ZonedDateTime getLvCheckDate() {
        return lvCheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.lv_check_date
     *
     * @param lvCheckDate the value for blocked_info.lv_check_date
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setLvCheckDate(ZonedDateTime lvCheckDate) {
        this.lvCheckDate = lvCheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.lv_check_state
     *
     * @return the value of blocked_info.lv_check_state
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getLvCheckState() {
        return lvCheckState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.lv_check_state
     *
     * @param lvCheckState the value for blocked_info.lv_check_state
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setLvCheckState(Long lvCheckState) {
        this.lvCheckState = lvCheckState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.base_checker
     *
     * @return the value of blocked_info.base_checker
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getBaseChecker() {
        return baseChecker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.base_checker
     *
     * @param baseChecker the value for blocked_info.base_checker
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setBaseChecker(Long baseChecker) {
        this.baseChecker = baseChecker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.base_check_date
     *
     * @return the value of blocked_info.base_check_date
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public ZonedDateTime getBaseCheckDate() {
        return baseCheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.base_check_date
     *
     * @param baseCheckDate the value for blocked_info.base_check_date
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setBaseCheckDate(ZonedDateTime baseCheckDate) {
        this.baseCheckDate = baseCheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.base_check_state
     *
     * @return the value of blocked_info.base_check_state
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getBaseCheckState() {
        return baseCheckState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.base_check_state
     *
     * @param baseCheckState the value for blocked_info.base_check_state
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setBaseCheckState(Long baseCheckState) {
        this.baseCheckState = baseCheckState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.modify_user
     *
     * @return the value of blocked_info.modify_user
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public Long getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.modify_user
     *
     * @param modifyUser the value for blocked_info.modify_user
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setModifyUser(Long modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_info.modify_date
     *
     * @return the value of blocked_info.modify_date
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public ZonedDateTime getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_info.modify_date
     *
     * @param modifyDate the value for blocked_info.modify_date
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    public void setModifyDate(ZonedDateTime modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_info
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BlockedInfo other = (BlockedInfo) that;
        return (this.getBlockedId() == null ? other.getBlockedId() == null : this.getBlockedId().equals(other.getBlockedId()))
            && (this.getIsValid() == null ? other.getIsValid() == null : this.getIsValid().equals(other.getIsValid()))
            && (this.getSpecilityType() == null ? other.getSpecilityType() == null : this.getSpecilityType().equals(other.getSpecilityType()))
            && (this.getTransLevel() == null ? other.getTransLevel() == null : this.getTransLevel().equals(other.getTransLevel()))
            && (this.getStartDate() == null ? other.getStartDate() == null : this.getStartDate().equals(other.getStartDate()))
            && (this.getStopDate() == null ? other.getStopDate() == null : this.getStopDate().equals(other.getStopDate()))
            && (this.getBlockedDuration() == null ? other.getBlockedDuration() == null : this.getBlockedDuration().equals(other.getBlockedDuration()))
            && (this.getAdminDistirctId() == null ? other.getAdminDistirctId() == null : this.getAdminDistirctId().equals(other.getAdminDistirctId()))
            && (this.getMaintOrgType() == null ? other.getMaintOrgType() == null : this.getMaintOrgType().equals(other.getMaintOrgType()))
            && (this.getMaintOrgId() == null ? other.getMaintOrgId() == null : this.getMaintOrgId().equals(other.getMaintOrgId()))
            && (this.getMaintOrg() == null ? other.getMaintOrg() == null : this.getMaintOrg().equals(other.getMaintOrg()))
            && (this.getChargeRange() == null ? other.getChargeRange() == null : this.getChargeRange().equals(other.getChargeRange()))
            && (this.getBlockedType() == null ? other.getBlockedType() == null : this.getBlockedType().equals(other.getBlockedType()))
            && (this.getBlockedReason() == null ? other.getBlockedReason() == null : this.getBlockedReason().equals(other.getBlockedReason()))
            && (this.getOptId() == null ? other.getOptId() == null : this.getOptId().equals(other.getOptId()))
            && (this.getOptName() == null ? other.getOptName() == null : this.getOptName().equals(other.getOptName()))
            && (this.getOptSegId() == null ? other.getOptSegId() == null : this.getOptSegId().equals(other.getOptSegId()))
            && (this.getOptSegName() == null ? other.getOptSegName() == null : this.getOptSegName().equals(other.getOptSegName()))
            && (this.getStationId() == null ? other.getStationId() == null : this.getStationId().equals(other.getStationId()))
            && (this.getStationName() == null ? other.getStationName() == null : this.getStationName().equals(other.getStationName()))
            && (this.getIsCntTimes() == null ? other.getIsCntTimes() == null : this.getIsCntTimes().equals(other.getIsCntTimes()))
            && (this.getIsCntDuration() == null ? other.getIsCntDuration() == null : this.getIsCntDuration().equals(other.getIsCntDuration()))
            && (this.getBlockedDetail() == null ? other.getBlockedDetail() == null : this.getBlockedDetail().equals(other.getBlockedDetail()))
            && (this.getAffactRange() == null ? other.getAffactRange() == null : this.getAffactRange().equals(other.getAffactRange()))
            && (this.getBlockedState() == null ? other.getBlockedState() == null : this.getBlockedState().equals(other.getBlockedState()))
            && (this.getClaimState() == null ? other.getClaimState() == null : this.getClaimState().equals(other.getClaimState()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
            && (this.getCommitDate() == null ? other.getCommitDate() == null : this.getCommitDate().equals(other.getCommitDate()))
            && (this.getLvChecker() == null ? other.getLvChecker() == null : this.getLvChecker().equals(other.getLvChecker()))
            && (this.getLvCheckDate() == null ? other.getLvCheckDate() == null : this.getLvCheckDate().equals(other.getLvCheckDate()))
            && (this.getLvCheckState() == null ? other.getLvCheckState() == null : this.getLvCheckState().equals(other.getLvCheckState()))
            && (this.getBaseChecker() == null ? other.getBaseChecker() == null : this.getBaseChecker().equals(other.getBaseChecker()))
            && (this.getBaseCheckDate() == null ? other.getBaseCheckDate() == null : this.getBaseCheckDate().equals(other.getBaseCheckDate()))
            && (this.getBaseCheckState() == null ? other.getBaseCheckState() == null : this.getBaseCheckState().equals(other.getBaseCheckState()))
            && (this.getModifyUser() == null ? other.getModifyUser() == null : this.getModifyUser().equals(other.getModifyUser()))
            && (this.getModifyDate() == null ? other.getModifyDate() == null : this.getModifyDate().equals(other.getModifyDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_info
     *
     * @mbg.generated Wed Oct 28 17:18:43 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBlockedId() == null) ? 0 : getBlockedId().hashCode());
        result = prime * result + ((getIsValid() == null) ? 0 : getIsValid().hashCode());
        result = prime * result + ((getSpecilityType() == null) ? 0 : getSpecilityType().hashCode());
        result = prime * result + ((getTransLevel() == null) ? 0 : getTransLevel().hashCode());
        result = prime * result + ((getStartDate() == null) ? 0 : getStartDate().hashCode());
        result = prime * result + ((getStopDate() == null) ? 0 : getStopDate().hashCode());
        result = prime * result + ((getBlockedDuration() == null) ? 0 : getBlockedDuration().hashCode());
        result = prime * result + ((getAdminDistirctId() == null) ? 0 : getAdminDistirctId().hashCode());
        result = prime * result + ((getMaintOrgType() == null) ? 0 : getMaintOrgType().hashCode());
        result = prime * result + ((getMaintOrgId() == null) ? 0 : getMaintOrgId().hashCode());
        result = prime * result + ((getMaintOrg() == null) ? 0 : getMaintOrg().hashCode());
        result = prime * result + ((getChargeRange() == null) ? 0 : getChargeRange().hashCode());
        result = prime * result + ((getBlockedType() == null) ? 0 : getBlockedType().hashCode());
        result = prime * result + ((getBlockedReason() == null) ? 0 : getBlockedReason().hashCode());
        result = prime * result + ((getOptId() == null) ? 0 : getOptId().hashCode());
        result = prime * result + ((getOptName() == null) ? 0 : getOptName().hashCode());
        result = prime * result + ((getOptSegId() == null) ? 0 : getOptSegId().hashCode());
        result = prime * result + ((getOptSegName() == null) ? 0 : getOptSegName().hashCode());
        result = prime * result + ((getStationId() == null) ? 0 : getStationId().hashCode());
        result = prime * result + ((getStationName() == null) ? 0 : getStationName().hashCode());
        result = prime * result + ((getIsCntTimes() == null) ? 0 : getIsCntTimes().hashCode());
        result = prime * result + ((getIsCntDuration() == null) ? 0 : getIsCntDuration().hashCode());
        result = prime * result + ((getBlockedDetail() == null) ? 0 : getBlockedDetail().hashCode());
        result = prime * result + ((getAffactRange() == null) ? 0 : getAffactRange().hashCode());
        result = prime * result + ((getBlockedState() == null) ? 0 : getBlockedState().hashCode());
        result = prime * result + ((getClaimState() == null) ? 0 : getClaimState().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        result = prime * result + ((getCommitDate() == null) ? 0 : getCommitDate().hashCode());
        result = prime * result + ((getLvChecker() == null) ? 0 : getLvChecker().hashCode());
        result = prime * result + ((getLvCheckDate() == null) ? 0 : getLvCheckDate().hashCode());
        result = prime * result + ((getLvCheckState() == null) ? 0 : getLvCheckState().hashCode());
        result = prime * result + ((getBaseChecker() == null) ? 0 : getBaseChecker().hashCode());
        result = prime * result + ((getBaseCheckDate() == null) ? 0 : getBaseCheckDate().hashCode());
        result = prime * result + ((getBaseCheckState() == null) ? 0 : getBaseCheckState().hashCode());
        result = prime * result + ((getModifyUser() == null) ? 0 : getModifyUser().hashCode());
        result = prime * result + ((getModifyDate() == null) ? 0 : getModifyDate().hashCode());
        return result;
    }

    @Override
    public String toString() {
        return "BlockedInfo{" +
                "blockedId=" + blockedId +
                ", isValid=" + isValid +
                ", specilityType=" + specilityType +
                ", transLevel=" + transLevel +
                ", startDate=" + startDate +
                ", stopDate=" + stopDate +
                ", blockedDuration=" + blockedDuration +
                ", adminDistirctId=" + adminDistirctId +
                ", maintOrgType=" + maintOrgType +
                ", maintOrgId=" + maintOrgId +
                ", maintOrg='" + maintOrg + '\'' +
                ", chargeRange=" + chargeRange +
                ", blockedType=" + blockedType +
                ", blockedReason=" + blockedReason +
                ", optId=" + optId +
                ", optName='" + optName + '\'' +
                ", optSegId=" + optSegId +
                ", optSegName='" + optSegName + '\'' +
                ", stationId=" + stationId +
                ", stationName='" + stationName + '\'' +
                ", isCntTimes=" + isCntTimes +
                ", isCntDuration=" + isCntDuration +
                ", blockedDetail='" + blockedDetail + '\'' +
                ", affactRange='" + affactRange + '\'' +
                ", blockedState=" + blockedState +
                ", claimState=" + claimState +
                ", userId=" + userId +
                ", orgId=" + orgId +
                ", commitDate=" + commitDate +
                ", lvChecker=" + lvChecker +
                ", lvCheckDate=" + lvCheckDate +
                ", lvCheckState=" + lvCheckState +
                ", baseChecker=" + baseChecker +
                ", baseCheckDate=" + baseCheckDate +
                ", baseCheckState=" + baseCheckState +
                ", modifyUser=" + modifyUser +
                ", modifyDate=" + modifyDate +
                '}';
    }
}