package com.ctsi.block.domain;

import java.io.Serializable;

/**
 * @author ctsi-biyi-generator
*/
public class BlockedImg implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_img.id
     *
     * @mbg.generated Wed Oct 28 17:18:33 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_img.blocked_id
     *
     * @mbg.generated Wed Oct 28 17:18:33 CST 2020
     */
    private Long blockedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_img.img_name
     *
     * @mbg.generated Wed Oct 28 17:18:33 CST 2020
     */
    private String imgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_img.img_path
     *
     * @mbg.generated Wed Oct 28 17:18:33 CST 2020
     */
    private String imgPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_img.id
     *
     * @return the value of blocked_img.id
     *
     * @mbg.generated Wed Oct 28 17:18:33 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_img.id
     *
     * @param id the value for blocked_img.id
     *
     * @mbg.generated Wed Oct 28 17:18:33 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_img.blocked_id
     *
     * @return the value of blocked_img.blocked_id
     *
     * @mbg.generated Wed Oct 28 17:18:33 CST 2020
     */
    public Long getBlockedId() {
        return blockedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_img.blocked_id
     *
     * @param blockedId the value for blocked_img.blocked_id
     *
     * @mbg.generated Wed Oct 28 17:18:33 CST 2020
     */
    public void setBlockedId(Long blockedId) {
        this.blockedId = blockedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_img.img_name
     *
     * @return the value of blocked_img.img_name
     *
     * @mbg.generated Wed Oct 28 17:18:33 CST 2020
     */
    public String getImgName() {
        return imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_img.img_name
     *
     * @param imgName the value for blocked_img.img_name
     *
     * @mbg.generated Wed Oct 28 17:18:33 CST 2020
     */
    public void setImgName(String imgName) {
        this.imgName = imgName == null ? null : imgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blocked_img.img_path
     *
     * @return the value of blocked_img.img_path
     *
     * @mbg.generated Wed Oct 28 17:18:33 CST 2020
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blocked_img.img_path
     *
     * @param imgPath the value for blocked_img.img_path
     *
     * @mbg.generated Wed Oct 28 17:18:33 CST 2020
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_img
     *
     * @mbg.generated Wed Oct 28 17:18:33 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BlockedImg other = (BlockedImg) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBlockedId() == null ? other.getBlockedId() == null : this.getBlockedId().equals(other.getBlockedId()))
            && (this.getImgName() == null ? other.getImgName() == null : this.getImgName().equals(other.getImgName()))
            && (this.getImgPath() == null ? other.getImgPath() == null : this.getImgPath().equals(other.getImgPath()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_img
     *
     * @mbg.generated Wed Oct 28 17:18:33 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBlockedId() == null) ? 0 : getBlockedId().hashCode());
        result = prime * result + ((getImgName() == null) ? 0 : getImgName().hashCode());
        result = prime * result + ((getImgPath() == null) ? 0 : getImgPath().hashCode());
        return result;
    }

    @Override
    public String toString() {
        return "BlockedImg{" +
                "id=" + id +
                ", blockedId=" + blockedId +
                ", imgName='" + imgName + '\'' +
                ", imgPath='" + imgPath + '\'' +
                '}';
    }
}