package com.ctsi.block.domain;

import com.ctsi.ssdc.criteria.LongCriteria;
import com.ctsi.ssdc.criteria.StringCriteria;
import com.ctsi.ssdc.example.BaseExample;
import io.swagger.annotations.ApiParam;
import java.util.ArrayList;
import java.util.List;
import org.apache.commons.lang3.StringUtils;

/**
 * @author ctsi-biyi-generator
*/
public class BlockedSystemExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    private static final String LIKE_FORMAT = "%%%s%%";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_system.affact_id
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    private LongCriteria affactId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_system.blocked_id
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    private LongCriteria blockedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_system.data_resource
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    private LongCriteria dataResource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_system.system_type
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    private LongCriteria systemType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_system.system_id
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    private LongCriteria systemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_system.system_name
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    private StringCriteria systemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_system.system_mark
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    private StringCriteria systemMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_system.system_level
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    private LongCriteria systemLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blocked_system.system_alias
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    private StringCriteria systemAlias;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public BlockedSystemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public LongCriteria getAffactId() {
        return affactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public void setAffactId(LongCriteria affactId) {
        this. affactId = affactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    private void buildAffactIdCriteria(Criteria criteria) {
        if (this.getAffactId() == null) {
            return;
        }
        if (this.getAffactId().getEquals() != null) {
            criteria.andAffactIdEqualTo(this.getAffactId().getEquals());
        } else {
            if (this.getAffactId().getGreaterOrEqualThan() != null) {
                criteria.andAffactIdGreaterThanOrEqualTo(this.getAffactId().getGreaterOrEqualThan());
            }
            if (this.getAffactId().getLessOrEqualThan() != null) {
                criteria.andAffactIdLessThanOrEqualTo(this.getAffactId().getLessOrEqualThan());
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public LongCriteria getBlockedId() {
        return blockedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public void setBlockedId(LongCriteria blockedId) {
        this. blockedId = blockedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    private void buildBlockedIdCriteria(Criteria criteria) {
        if (this.getBlockedId() == null) {
            return;
        }
        if (this.getBlockedId().getEquals() != null) {
            criteria.andBlockedIdEqualTo(this.getBlockedId().getEquals());
        } else {
            if (this.getBlockedId().getGreaterOrEqualThan() != null) {
                criteria.andBlockedIdGreaterThanOrEqualTo(this.getBlockedId().getGreaterOrEqualThan());
            }
            if (this.getBlockedId().getLessOrEqualThan() != null) {
                criteria.andBlockedIdLessThanOrEqualTo(this.getBlockedId().getLessOrEqualThan());
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public LongCriteria getDataResource() {
        return dataResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public void setDataResource(LongCriteria dataResource) {
        this. dataResource = dataResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    private void buildDataResourceCriteria(Criteria criteria) {
        if (this.getDataResource() == null) {
            return;
        }
        if (this.getDataResource().getEquals() != null) {
            criteria.andDataResourceEqualTo(this.getDataResource().getEquals());
        } else {
            if (this.getDataResource().getGreaterOrEqualThan() != null) {
                criteria.andDataResourceGreaterThanOrEqualTo(this.getDataResource().getGreaterOrEqualThan());
            }
            if (this.getDataResource().getLessOrEqualThan() != null) {
                criteria.andDataResourceLessThanOrEqualTo(this.getDataResource().getLessOrEqualThan());
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public LongCriteria getSystemType() {
        return systemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public void setSystemType(LongCriteria systemType) {
        this. systemType = systemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    private void buildSystemTypeCriteria(Criteria criteria) {
        if (this.getSystemType() == null) {
            return;
        }
        if (this.getSystemType().getEquals() != null) {
            criteria.andSystemTypeEqualTo(this.getSystemType().getEquals());
        } else {
            if (this.getSystemType().getGreaterOrEqualThan() != null) {
                criteria.andSystemTypeGreaterThanOrEqualTo(this.getSystemType().getGreaterOrEqualThan());
            }
            if (this.getSystemType().getLessOrEqualThan() != null) {
                criteria.andSystemTypeLessThanOrEqualTo(this.getSystemType().getLessOrEqualThan());
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public LongCriteria getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public void setSystemId(LongCriteria systemId) {
        this. systemId = systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    private void buildSystemIdCriteria(Criteria criteria) {
        if (this.getSystemId() == null) {
            return;
        }
        if (this.getSystemId().getEquals() != null) {
            criteria.andSystemIdEqualTo(this.getSystemId().getEquals());
        } else {
            if (this.getSystemId().getGreaterOrEqualThan() != null) {
                criteria.andSystemIdGreaterThanOrEqualTo(this.getSystemId().getGreaterOrEqualThan());
            }
            if (this.getSystemId().getLessOrEqualThan() != null) {
                criteria.andSystemIdLessThanOrEqualTo(this.getSystemId().getLessOrEqualThan());
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public StringCriteria getSystemName() {
        return systemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public void setSystemName(StringCriteria systemName) {
        this. systemName = systemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    private void buildSystemNameCriteria(Criteria criteria) {
        if (this.getSystemName() == null) {
            return;
        }
        if (this.getSystemName().getEquals() != null) {
            criteria.andSystemNameEqualTo(this.getSystemName().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getSystemName().getContains())) {
                criteria.andSystemNameLike(String.format(LIKE_FORMAT, this.getSystemName().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public StringCriteria getSystemMark() {
        return systemMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public void setSystemMark(StringCriteria systemMark) {
        this. systemMark = systemMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    private void buildSystemMarkCriteria(Criteria criteria) {
        if (this.getSystemMark() == null) {
            return;
        }
        if (this.getSystemMark().getEquals() != null) {
            criteria.andSystemMarkEqualTo(this.getSystemMark().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getSystemMark().getContains())) {
                criteria.andSystemMarkLike(String.format(LIKE_FORMAT, this.getSystemMark().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public LongCriteria getSystemLevel() {
        return systemLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public void setSystemLevel(LongCriteria systemLevel) {
        this. systemLevel = systemLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    private void buildSystemLevelCriteria(Criteria criteria) {
        if (this.getSystemLevel() == null) {
            return;
        }
        if (this.getSystemLevel().getEquals() != null) {
            criteria.andSystemLevelEqualTo(this.getSystemLevel().getEquals());
        } else {
            if (this.getSystemLevel().getGreaterOrEqualThan() != null) {
                criteria.andSystemLevelGreaterThanOrEqualTo(this.getSystemLevel().getGreaterOrEqualThan());
            }
            if (this.getSystemLevel().getLessOrEqualThan() != null) {
                criteria.andSystemLevelLessThanOrEqualTo(this.getSystemLevel().getLessOrEqualThan());
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public StringCriteria getSystemAlias() {
        return systemAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public void setSystemAlias(StringCriteria systemAlias) {
        this. systemAlias = systemAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    private void buildSystemAliasCriteria(Criteria criteria) {
        if (this.getSystemAlias() == null) {
            return;
        }
        if (this.getSystemAlias().getEquals() != null) {
            criteria.andSystemAliasEqualTo(this.getSystemAlias().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getSystemAlias().getContains())) {
                criteria.andSystemAliasLike(String.format(LIKE_FORMAT, this.getSystemAlias().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public Object buildCriteria() {
        Criteria criteria = this.createCriteria();
        this.buildAffactIdCriteria(criteria);
        this.buildBlockedIdCriteria(criteria);
        this.buildDataResourceCriteria(criteria);
        this.buildSystemTypeCriteria(criteria);
        this.buildSystemIdCriteria(criteria);
        this.buildSystemNameCriteria(criteria);
        this.buildSystemMarkCriteria(criteria);
        this.buildSystemLevelCriteria(criteria);
        this.buildSystemAliasCriteria(criteria);
        return criteria;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAffactIdIsNull() {
            addCriterion("affact_id is null");
            return (Criteria) this;
        }

        public Criteria andAffactIdIsNotNull() {
            addCriterion("affact_id is not null");
            return (Criteria) this;
        }

        public Criteria andAffactIdEqualTo(Long value) {
            addCriterion("affact_id =", value, "affactId");
            return (Criteria) this;
        }

        public Criteria andAffactIdNotEqualTo(Long value) {
            addCriterion("affact_id <>", value, "affactId");
            return (Criteria) this;
        }

        public Criteria andAffactIdGreaterThan(Long value) {
            addCriterion("affact_id >", value, "affactId");
            return (Criteria) this;
        }

        public Criteria andAffactIdGreaterThanOrEqualTo(Long value) {
            addCriterion("affact_id >=", value, "affactId");
            return (Criteria) this;
        }

        public Criteria andAffactIdLessThan(Long value) {
            addCriterion("affact_id <", value, "affactId");
            return (Criteria) this;
        }

        public Criteria andAffactIdLessThanOrEqualTo(Long value) {
            addCriterion("affact_id <=", value, "affactId");
            return (Criteria) this;
        }

        public Criteria andAffactIdIn(List<Long> values) {
            addCriterion("affact_id in", values, "affactId");
            return (Criteria) this;
        }

        public Criteria andAffactIdNotIn(List<Long> values) {
            addCriterion("affact_id not in", values, "affactId");
            return (Criteria) this;
        }

        public Criteria andAffactIdBetween(Long value1, Long value2) {
            addCriterion("affact_id between", value1, value2, "affactId");
            return (Criteria) this;
        }

        public Criteria andAffactIdNotBetween(Long value1, Long value2) {
            addCriterion("affact_id not between", value1, value2, "affactId");
            return (Criteria) this;
        }

        public Criteria andBlockedIdIsNull() {
            addCriterion("blocked_id is null");
            return (Criteria) this;
        }

        public Criteria andBlockedIdIsNotNull() {
            addCriterion("blocked_id is not null");
            return (Criteria) this;
        }

        public Criteria andBlockedIdEqualTo(Long value) {
            addCriterion("blocked_id =", value, "blockedId");
            return (Criteria) this;
        }

        public Criteria andBlockedIdNotEqualTo(Long value) {
            addCriterion("blocked_id <>", value, "blockedId");
            return (Criteria) this;
        }

        public Criteria andBlockedIdGreaterThan(Long value) {
            addCriterion("blocked_id >", value, "blockedId");
            return (Criteria) this;
        }

        public Criteria andBlockedIdGreaterThanOrEqualTo(Long value) {
            addCriterion("blocked_id >=", value, "blockedId");
            return (Criteria) this;
        }

        public Criteria andBlockedIdLessThan(Long value) {
            addCriterion("blocked_id <", value, "blockedId");
            return (Criteria) this;
        }

        public Criteria andBlockedIdLessThanOrEqualTo(Long value) {
            addCriterion("blocked_id <=", value, "blockedId");
            return (Criteria) this;
        }

        public Criteria andBlockedIdIn(List<Long> values) {
            addCriterion("blocked_id in", values, "blockedId");
            return (Criteria) this;
        }

        public Criteria andBlockedIdNotIn(List<Long> values) {
            addCriterion("blocked_id not in", values, "blockedId");
            return (Criteria) this;
        }

        public Criteria andBlockedIdBetween(Long value1, Long value2) {
            addCriterion("blocked_id between", value1, value2, "blockedId");
            return (Criteria) this;
        }

        public Criteria andBlockedIdNotBetween(Long value1, Long value2) {
            addCriterion("blocked_id not between", value1, value2, "blockedId");
            return (Criteria) this;
        }

        public Criteria andDataResourceIsNull() {
            addCriterion("data_resource is null");
            return (Criteria) this;
        }

        public Criteria andDataResourceIsNotNull() {
            addCriterion("data_resource is not null");
            return (Criteria) this;
        }

        public Criteria andDataResourceEqualTo(Long value) {
            addCriterion("data_resource =", value, "dataResource");
            return (Criteria) this;
        }

        public Criteria andDataResourceNotEqualTo(Long value) {
            addCriterion("data_resource <>", value, "dataResource");
            return (Criteria) this;
        }

        public Criteria andDataResourceGreaterThan(Long value) {
            addCriterion("data_resource >", value, "dataResource");
            return (Criteria) this;
        }

        public Criteria andDataResourceGreaterThanOrEqualTo(Long value) {
            addCriterion("data_resource >=", value, "dataResource");
            return (Criteria) this;
        }

        public Criteria andDataResourceLessThan(Long value) {
            addCriterion("data_resource <", value, "dataResource");
            return (Criteria) this;
        }

        public Criteria andDataResourceLessThanOrEqualTo(Long value) {
            addCriterion("data_resource <=", value, "dataResource");
            return (Criteria) this;
        }

        public Criteria andDataResourceIn(List<Long> values) {
            addCriterion("data_resource in", values, "dataResource");
            return (Criteria) this;
        }

        public Criteria andDataResourceNotIn(List<Long> values) {
            addCriterion("data_resource not in", values, "dataResource");
            return (Criteria) this;
        }

        public Criteria andDataResourceBetween(Long value1, Long value2) {
            addCriterion("data_resource between", value1, value2, "dataResource");
            return (Criteria) this;
        }

        public Criteria andDataResourceNotBetween(Long value1, Long value2) {
            addCriterion("data_resource not between", value1, value2, "dataResource");
            return (Criteria) this;
        }

        public Criteria andSystemTypeIsNull() {
            addCriterion("system_type is null");
            return (Criteria) this;
        }

        public Criteria andSystemTypeIsNotNull() {
            addCriterion("system_type is not null");
            return (Criteria) this;
        }

        public Criteria andSystemTypeEqualTo(Long value) {
            addCriterion("system_type =", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeNotEqualTo(Long value) {
            addCriterion("system_type <>", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeGreaterThan(Long value) {
            addCriterion("system_type >", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeGreaterThanOrEqualTo(Long value) {
            addCriterion("system_type >=", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeLessThan(Long value) {
            addCriterion("system_type <", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeLessThanOrEqualTo(Long value) {
            addCriterion("system_type <=", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeIn(List<Long> values) {
            addCriterion("system_type in", values, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeNotIn(List<Long> values) {
            addCriterion("system_type not in", values, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeBetween(Long value1, Long value2) {
            addCriterion("system_type between", value1, value2, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeNotBetween(Long value1, Long value2) {
            addCriterion("system_type not between", value1, value2, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemIdIsNull() {
            addCriterion("system_id is null");
            return (Criteria) this;
        }

        public Criteria andSystemIdIsNotNull() {
            addCriterion("system_id is not null");
            return (Criteria) this;
        }

        public Criteria andSystemIdEqualTo(Long value) {
            addCriterion("system_id =", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdNotEqualTo(Long value) {
            addCriterion("system_id <>", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdGreaterThan(Long value) {
            addCriterion("system_id >", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdGreaterThanOrEqualTo(Long value) {
            addCriterion("system_id >=", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdLessThan(Long value) {
            addCriterion("system_id <", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdLessThanOrEqualTo(Long value) {
            addCriterion("system_id <=", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdIn(List<Long> values) {
            addCriterion("system_id in", values, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdNotIn(List<Long> values) {
            addCriterion("system_id not in", values, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdBetween(Long value1, Long value2) {
            addCriterion("system_id between", value1, value2, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdNotBetween(Long value1, Long value2) {
            addCriterion("system_id not between", value1, value2, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemNameIsNull() {
            addCriterion("system_name is null");
            return (Criteria) this;
        }

        public Criteria andSystemNameIsNotNull() {
            addCriterion("system_name is not null");
            return (Criteria) this;
        }

        public Criteria andSystemNameEqualTo(String value) {
            addCriterion("system_name =", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameNotEqualTo(String value) {
            addCriterion("system_name <>", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameGreaterThan(String value) {
            addCriterion("system_name >", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameGreaterThanOrEqualTo(String value) {
            addCriterion("system_name >=", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameLessThan(String value) {
            addCriterion("system_name <", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameLessThanOrEqualTo(String value) {
            addCriterion("system_name <=", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameLike(String value) {
            addCriterion("system_name like", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameNotLike(String value) {
            addCriterion("system_name not like", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameIn(List<String> values) {
            addCriterion("system_name in", values, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameNotIn(List<String> values) {
            addCriterion("system_name not in", values, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameBetween(String value1, String value2) {
            addCriterion("system_name between", value1, value2, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameNotBetween(String value1, String value2) {
            addCriterion("system_name not between", value1, value2, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemMarkIsNull() {
            addCriterion("system_mark is null");
            return (Criteria) this;
        }

        public Criteria andSystemMarkIsNotNull() {
            addCriterion("system_mark is not null");
            return (Criteria) this;
        }

        public Criteria andSystemMarkEqualTo(String value) {
            addCriterion("system_mark =", value, "systemMark");
            return (Criteria) this;
        }

        public Criteria andSystemMarkNotEqualTo(String value) {
            addCriterion("system_mark <>", value, "systemMark");
            return (Criteria) this;
        }

        public Criteria andSystemMarkGreaterThan(String value) {
            addCriterion("system_mark >", value, "systemMark");
            return (Criteria) this;
        }

        public Criteria andSystemMarkGreaterThanOrEqualTo(String value) {
            addCriterion("system_mark >=", value, "systemMark");
            return (Criteria) this;
        }

        public Criteria andSystemMarkLessThan(String value) {
            addCriterion("system_mark <", value, "systemMark");
            return (Criteria) this;
        }

        public Criteria andSystemMarkLessThanOrEqualTo(String value) {
            addCriterion("system_mark <=", value, "systemMark");
            return (Criteria) this;
        }

        public Criteria andSystemMarkLike(String value) {
            addCriterion("system_mark like", value, "systemMark");
            return (Criteria) this;
        }

        public Criteria andSystemMarkNotLike(String value) {
            addCriterion("system_mark not like", value, "systemMark");
            return (Criteria) this;
        }

        public Criteria andSystemMarkIn(List<String> values) {
            addCriterion("system_mark in", values, "systemMark");
            return (Criteria) this;
        }

        public Criteria andSystemMarkNotIn(List<String> values) {
            addCriterion("system_mark not in", values, "systemMark");
            return (Criteria) this;
        }

        public Criteria andSystemMarkBetween(String value1, String value2) {
            addCriterion("system_mark between", value1, value2, "systemMark");
            return (Criteria) this;
        }

        public Criteria andSystemMarkNotBetween(String value1, String value2) {
            addCriterion("system_mark not between", value1, value2, "systemMark");
            return (Criteria) this;
        }

        public Criteria andSystemLevelIsNull() {
            addCriterion("system_level is null");
            return (Criteria) this;
        }

        public Criteria andSystemLevelIsNotNull() {
            addCriterion("system_level is not null");
            return (Criteria) this;
        }

        public Criteria andSystemLevelEqualTo(Long value) {
            addCriterion("system_level =", value, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemLevelNotEqualTo(Long value) {
            addCriterion("system_level <>", value, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemLevelGreaterThan(Long value) {
            addCriterion("system_level >", value, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemLevelGreaterThanOrEqualTo(Long value) {
            addCriterion("system_level >=", value, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemLevelLessThan(Long value) {
            addCriterion("system_level <", value, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemLevelLessThanOrEqualTo(Long value) {
            addCriterion("system_level <=", value, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemLevelIn(List<Long> values) {
            addCriterion("system_level in", values, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemLevelNotIn(List<Long> values) {
            addCriterion("system_level not in", values, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemLevelBetween(Long value1, Long value2) {
            addCriterion("system_level between", value1, value2, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemLevelNotBetween(Long value1, Long value2) {
            addCriterion("system_level not between", value1, value2, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemAliasIsNull() {
            addCriterion("system_alias is null");
            return (Criteria) this;
        }

        public Criteria andSystemAliasIsNotNull() {
            addCriterion("system_alias is not null");
            return (Criteria) this;
        }

        public Criteria andSystemAliasEqualTo(String value) {
            addCriterion("system_alias =", value, "systemAlias");
            return (Criteria) this;
        }

        public Criteria andSystemAliasNotEqualTo(String value) {
            addCriterion("system_alias <>", value, "systemAlias");
            return (Criteria) this;
        }

        public Criteria andSystemAliasGreaterThan(String value) {
            addCriterion("system_alias >", value, "systemAlias");
            return (Criteria) this;
        }

        public Criteria andSystemAliasGreaterThanOrEqualTo(String value) {
            addCriterion("system_alias >=", value, "systemAlias");
            return (Criteria) this;
        }

        public Criteria andSystemAliasLessThan(String value) {
            addCriterion("system_alias <", value, "systemAlias");
            return (Criteria) this;
        }

        public Criteria andSystemAliasLessThanOrEqualTo(String value) {
            addCriterion("system_alias <=", value, "systemAlias");
            return (Criteria) this;
        }

        public Criteria andSystemAliasLike(String value) {
            addCriterion("system_alias like", value, "systemAlias");
            return (Criteria) this;
        }

        public Criteria andSystemAliasNotLike(String value) {
            addCriterion("system_alias not like", value, "systemAlias");
            return (Criteria) this;
        }

        public Criteria andSystemAliasIn(List<String> values) {
            addCriterion("system_alias in", values, "systemAlias");
            return (Criteria) this;
        }

        public Criteria andSystemAliasNotIn(List<String> values) {
            addCriterion("system_alias not in", values, "systemAlias");
            return (Criteria) this;
        }

        public Criteria andSystemAliasBetween(String value1, String value2) {
            addCriterion("system_alias between", value1, value2, "systemAlias");
            return (Criteria) this;
        }

        public Criteria andSystemAliasNotBetween(String value1, String value2) {
            addCriterion("system_alias not between", value1, value2, "systemAlias");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table blocked_system
     *
     * @mbg.generated do_not_delete_during_merge Wed Oct 28 17:18:56 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table blocked_system
     *
     * @mbg.generated Wed Oct 28 17:18:56 CST 2020
     */
    public static class Criterion {
        @ApiParam(hidden=true)
        private String condition;

        @ApiParam(hidden=true)
        private Object value;

        @ApiParam(hidden=true)
        private Object secondValue;

        @ApiParam(hidden=true)
        private boolean noValue;

        @ApiParam(hidden=true)
        private boolean singleValue;

        @ApiParam(hidden=true)
        private boolean betweenValue;

        @ApiParam(hidden=true)
        private boolean listValue;

        @ApiParam(hidden=true)
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}