package com.ctsi.space.repository;

import com.ctsi.space.domain.BasProtectedUser;
import com.ctsi.space.domain.BasProtectedUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

/**
 * @author ctsi-biyi-generator
 */
@Mapper
public interface BasProtectedUserRepository extends com.ctsi.ssdc.repository.BaseRepository<BasProtectedUser, Long, BasProtectedUserExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protected_user
     *
     * @mbg.generated Thu Sep 24 14:35:22 CST 2020
     */
    @SelectProvider(type=BasProtectedUserSqlProvider.class, method="countByExample")
    long countByExample(BasProtectedUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protected_user
     *
     * @mbg.generated Thu Sep 24 14:35:22 CST 2020
     */
    @DeleteProvider(type=BasProtectedUserSqlProvider.class, method="deleteByExample")
    int deleteByExample(BasProtectedUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protected_user
     *
     * @mbg.generated Thu Sep 24 14:35:22 CST 2020
     */
    @Delete({
            "delete from bas_protected_user",
            "where user_id = #{userId,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protected_user
     *
     * @mbg.generated Thu Sep 24 14:35:22 CST 2020
     */
    @Insert({
            "insert into bas_protected_user (user_id, user_name, ",
            "user_full_name, user_level, ",
            "area, address, connect_user, ",
            "connect_tel, armt_type, ",
            "is_valid, note, cus_id, ",
            "user_type, armt_name, ",
            "user_mark, cus_type)",
            "values (#{userId,jdbcType=DECIMAL}, #{userName,jdbcType=VARCHAR}, ",
            "#{userFullName,jdbcType=VARCHAR}, #{userLevel,jdbcType=DECIMAL}, ",
            "#{area,jdbcType=DECIMAL}, #{address,jdbcType=VARCHAR}, #{connectUser,jdbcType=VARCHAR}, ",
            "#{connectTel,jdbcType=VARCHAR}, #{armtType,jdbcType=DECIMAL}, ",
            "#{isValid,jdbcType=DECIMAL}, #{note,jdbcType=VARCHAR}, #{cusId,jdbcType=DECIMAL}, ",
            "#{userType,jdbcType=DECIMAL}, #{armtName,jdbcType=VARCHAR}, ",
            "#{userMark,jdbcType=DECIMAL}, #{cusType,jdbcType=INTEGER})"
    })
    int insert(BasProtectedUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protected_user
     *
     * @mbg.generated Thu Sep 24 14:35:22 CST 2020
     */
    @InsertProvider(type=BasProtectedUserSqlProvider.class, method="insertSelective")
    int insertSelective(BasProtectedUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protected_user
     *
     * @mbg.generated Thu Sep 24 14:35:22 CST 2020
     */
    @SelectProvider(type=BasProtectedUserSqlProvider.class, method="selectByExample")
    @Results({
            @Result(column="user_id", property="userId", jdbcType=JdbcType.DECIMAL, id=true),
            @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
            @Result(column="user_full_name", property="userFullName", jdbcType=JdbcType.VARCHAR),
            @Result(column="user_level", property="userLevel", jdbcType=JdbcType.DECIMAL),
            @Result(column="area", property="area", jdbcType=JdbcType.DECIMAL),
            @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
            @Result(column="connect_user", property="connectUser", jdbcType=JdbcType.VARCHAR),
            @Result(column="connect_tel", property="connectTel", jdbcType=JdbcType.VARCHAR),
            @Result(column="armt_type", property="armtType", jdbcType=JdbcType.DECIMAL),
            @Result(column="is_valid", property="isValid", jdbcType=JdbcType.DECIMAL),
            @Result(column="note", property="note", jdbcType=JdbcType.VARCHAR),
            @Result(column="cus_id", property="cusId", jdbcType=JdbcType.DECIMAL),
            @Result(column="user_type", property="userType", jdbcType=JdbcType.DECIMAL),
            @Result(column="armt_name", property="armtName", jdbcType=JdbcType.VARCHAR),
            @Result(column="user_mark", property="userMark", jdbcType=JdbcType.DECIMAL),
            @Result(column="cus_type", property="cusType", jdbcType=JdbcType.INTEGER)
    })
    List<BasProtectedUser> selectByExample(BasProtectedUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protected_user
     *
     * @mbg.generated Thu Sep 24 14:35:22 CST 2020
     */
    @Select({
            "select",
            "user_id, user_name, user_full_name, user_level, area, address, connect_user, ",
            "connect_tel, armt_type, is_valid, note, cus_id, user_type, armt_name, user_mark, ",
            "cus_type",
            "from bas_protected_user",
            "where user_id = #{userId,jdbcType=DECIMAL}"
    })
    @Results({
            @Result(column="user_id", property="userId", jdbcType=JdbcType.DECIMAL, id=true),
            @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
            @Result(column="user_full_name", property="userFullName", jdbcType=JdbcType.VARCHAR),
            @Result(column="user_level", property="userLevel", jdbcType=JdbcType.DECIMAL),
            @Result(column="area", property="area", jdbcType=JdbcType.DECIMAL),
            @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
            @Result(column="connect_user", property="connectUser", jdbcType=JdbcType.VARCHAR),
            @Result(column="connect_tel", property="connectTel", jdbcType=JdbcType.VARCHAR),
            @Result(column="armt_type", property="armtType", jdbcType=JdbcType.DECIMAL),
            @Result(column="is_valid", property="isValid", jdbcType=JdbcType.DECIMAL),
            @Result(column="note", property="note", jdbcType=JdbcType.VARCHAR),
            @Result(column="cus_id", property="cusId", jdbcType=JdbcType.DECIMAL),
            @Result(column="user_type", property="userType", jdbcType=JdbcType.DECIMAL),
            @Result(column="armt_name", property="armtName", jdbcType=JdbcType.VARCHAR),
            @Result(column="user_mark", property="userMark", jdbcType=JdbcType.DECIMAL),
            @Result(column="cus_type", property="cusType", jdbcType=JdbcType.INTEGER)
    })
    BasProtectedUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protected_user
     *
     * @mbg.generated Thu Sep 24 14:35:22 CST 2020
     */
    @UpdateProvider(type=BasProtectedUserSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BasProtectedUser record, @Param("example") BasProtectedUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protected_user
     *
     * @mbg.generated Thu Sep 24 14:35:22 CST 2020
     */
    @UpdateProvider(type=BasProtectedUserSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BasProtectedUser record, @Param("example") BasProtectedUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protected_user
     *
     * @mbg.generated Thu Sep 24 14:35:22 CST 2020
     */
    @UpdateProvider(type=BasProtectedUserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BasProtectedUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protected_user
     *
     * @mbg.generated Thu Sep 24 14:35:22 CST 2020
     */
    @Update({
            "update bas_protected_user",
            "set user_name = #{userName,jdbcType=VARCHAR},",
            "user_full_name = #{userFullName,jdbcType=VARCHAR},",
            "user_level = #{userLevel,jdbcType=DECIMAL},",
            "area = #{area,jdbcType=DECIMAL},",
            "address = #{address,jdbcType=VARCHAR},",
            "connect_user = #{connectUser,jdbcType=VARCHAR},",
            "connect_tel = #{connectTel,jdbcType=VARCHAR},",
            "armt_type = #{armtType,jdbcType=DECIMAL},",
            "is_valid = #{isValid,jdbcType=DECIMAL},",
            "note = #{note,jdbcType=VARCHAR},",
            "cus_id = #{cusId,jdbcType=DECIMAL},",
            "user_type = #{userType,jdbcType=DECIMAL},",
            "armt_name = #{armtName,jdbcType=VARCHAR},",
            "user_mark = #{userMark,jdbcType=DECIMAL},",
            "cus_type = #{cusType,jdbcType=INTEGER}",
            "where user_id = #{userId,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(BasProtectedUser record);
}