package com.ctsi.space.repository;

import com.ctsi.space.domain.BasProtectUserRelationship;
import com.ctsi.space.domain.BasProtectUserRelationshipExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

/**
 * @author ctsi-biyi-generator
*/
@Mapper
public interface BasProtectUserRelationshipRepository extends com.ctsi.ssdc.repository.BaseRepository<BasProtectUserRelationship, Long, BasProtectUserRelationshipExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protect_user_relationship
     *
     * @mbg.generated Fri Sep 11 16:09:31 CST 2020
     */
    @SelectProvider(type=BasProtectUserRelationshipSqlProvider.class, method="countByExample")
    long countByExample(BasProtectUserRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protect_user_relationship
     *
     * @mbg.generated Fri Sep 11 16:09:31 CST 2020
     */
    @DeleteProvider(type=BasProtectUserRelationshipSqlProvider.class, method="deleteByExample")
    int deleteByExample(BasProtectUserRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protect_user_relationship
     *
     * @mbg.generated Fri Sep 11 16:09:31 CST 2020
     */
    @Delete({
        "delete from bas_protect_user_relationship",
        "where relationship_id = #{relationshipId,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Long relationshipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protect_user_relationship
     *
     * @mbg.generated Fri Sep 11 16:09:31 CST 2020
     */
    @Insert({
        "insert into bas_protect_user_relationship (relationship_id, protect_user_id, ",
        "user_id)",
        "values (#{relationshipId,jdbcType=DECIMAL}, #{protectUserId,jdbcType=DECIMAL}, ",
        "#{userId,jdbcType=DECIMAL})"
    })
    int insert(BasProtectUserRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protect_user_relationship
     *
     * @mbg.generated Fri Sep 11 16:09:31 CST 2020
     */
    @InsertProvider(type=BasProtectUserRelationshipSqlProvider.class, method="insertSelective")
    int insertSelective(BasProtectUserRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protect_user_relationship
     *
     * @mbg.generated Fri Sep 11 16:09:31 CST 2020
     */
    @SelectProvider(type=BasProtectUserRelationshipSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="relationship_id", property="relationshipId", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="protect_user_id", property="protectUserId", jdbcType=JdbcType.DECIMAL),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.DECIMAL)
    })
    List<BasProtectUserRelationship> selectByExample(BasProtectUserRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protect_user_relationship
     *
     * @mbg.generated Fri Sep 11 16:09:31 CST 2020
     */
    @Select({
        "select",
        "relationship_id, protect_user_id, user_id",
        "from bas_protect_user_relationship",
        "where relationship_id = #{relationshipId,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="relationship_id", property="relationshipId", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="protect_user_id", property="protectUserId", jdbcType=JdbcType.DECIMAL),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.DECIMAL)
    })
    BasProtectUserRelationship selectByPrimaryKey(Long relationshipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protect_user_relationship
     *
     * @mbg.generated Fri Sep 11 16:09:31 CST 2020
     */
    @UpdateProvider(type=BasProtectUserRelationshipSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BasProtectUserRelationship record, @Param("example") BasProtectUserRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protect_user_relationship
     *
     * @mbg.generated Fri Sep 11 16:09:31 CST 2020
     */
    @UpdateProvider(type=BasProtectUserRelationshipSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BasProtectUserRelationship record, @Param("example") BasProtectUserRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protect_user_relationship
     *
     * @mbg.generated Fri Sep 11 16:09:31 CST 2020
     */
    @UpdateProvider(type=BasProtectUserRelationshipSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BasProtectUserRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_protect_user_relationship
     *
     * @mbg.generated Fri Sep 11 16:09:31 CST 2020
     */
    @Update({
        "update bas_protect_user_relationship",
        "set protect_user_id = #{protectUserId,jdbcType=DECIMAL},",
          "user_id = #{userId,jdbcType=DECIMAL}",
        "where relationship_id = #{relationshipId,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(BasProtectUserRelationship record);
}